server:
  port: 8390
  servlet:
    context-path: /notifications

logging:
  config: classpath:log4j2.xml

spring:
  banner:
    location: classpath:banner.txt
  security:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    permit:
      all: /actuator, /actuator/**, /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html
  datasource:
    url: jdbc:postgresql://localhost:5500/bookshop_db
    username: postgres
    password: postgres
    driver-class-name: 'org.postgresql.Driver'
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 120000 # 2 min
            readTimeout: 120000 # 2 min
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: bookshopztpai@gmail.com
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# GPT service client
gpt-service:
  http-client:
    read-timeout: 120000
    connect-timeout: 120000
  urls:
    base-url: http://localhost:8490/gptclient
    generate-welcome-message: /api/v1/notifications/generate/welcomeMessage

# actuator
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  health:
    circuitbreakers:
      enabled: true